'use strict';
const{DateTime}=require('luxon');const{resolveRange,rangesFor}=require('./ranges');const{applyFilters}=require('../sales/sales.service');
function colorForCode(code){let hash=0;for(const ch of String(code))hash=(hash*31+ch.charCodeAt(0))>>>0;return`hsl(${hash%360} 62% 48%)`;}
function baseQuery(db,filters,range){const q=db('sales').join('sellers','sellers.id','sales.seller_id').join('services','services.id','sales.service_id').join('operators','operators.id','sales.operator_id').join('sale_types','sale_types.id','sales.sale_type_id');return applyFilters(q,{...filters,start_date:range.start,end_date:range.end});}
async function aggregate(db,filters,range){
  const base=baseQuery(db,filters,range);
  const totals=await base.clone().clearSelect().select(db.raw('COALESCE(SUM(sales.quantity),0) AS units'),db.raw('COALESCE(SUM(sales.total_value),0) AS revenue'),db.raw('COUNT(*) AS records'),db.raw('SUM(sales.has_doc = 1) AS with_doc_records'),db.raw('SUM(sales.has_doc = 0) AS without_doc_records')).first();
  const shifts=await base.clone().clearSelect().select('sales.sale_shift').count({records:'sales.id'}).sum({units:'sales.quantity',revenue:'sales.total_value'}).sum({with_doc_records:db.raw('sales.has_doc = 1'),without_doc_records:db.raw('sales.has_doc = 0')}).groupBy('sales.sale_shift');
  const operators=await base.clone().clearSelect().select('operators.id','operators.code','operators.name').sum({units:'sales.quantity',revenue:'sales.total_value'}).groupBy('operators.id','operators.code','operators.name').orderBy('revenue','desc');
  const categories=await base.clone().clearSelect().select('sale_types.code','sales.is_base_sale').sum({revenue:'sales.total_value'}).groupBy('sale_types.code','sales.is_base_sale');
  const ranking=await base.clone().clearSelect().select('sellers.id as seller_id','sellers.full_name','sellers.photo_media_id').sum({revenue:'sales.total_value',units:'sales.quantity'}).min({first_sale:db.raw("CONCAT(sales.sale_date,' ',sales.sale_time)")}).groupBy('sellers.id','sellers.full_name','sellers.photo_media_id');
  ranking.sort(require('../sales/ranking').compareRanking);
  const revenue=Number(totals.revenue||0),units=Number(totals.units||0);
  return{totals:{records:Number(totals.records||0),units,revenue,ticket:units?revenue/units:0,withDocRecords:Number(totals.with_doc_records||0),withoutDocRecords:Number(totals.without_doc_records||0)},shifts:Object.fromEntries(shifts.map(r=>[r.sale_shift,{records:Number(r.records),units:Number(r.units||0),revenue:Number(r.revenue||0),withDocRecords:Number(r.with_doc_records||0),withoutDocRecords:Number(r.without_doc_records||0)}])),operators:operators.map(r=>({...r,units:Number(r.units||0),revenue:Number(r.revenue||0),color:colorForCode(r.code)})),categories:Object.fromEntries(categories.map(r=>[`${r.code}_${r.is_base_sale?'base':'out'}`,Number(r.revenue||0)])),ranking:ranking.map((r,index)=>({...r,position:index+1,revenue:Number(r.revenue),units:Number(r.units)}))};
}
async function targetFor(db,range,sellerId){
  const period=await db('goal_periods').where({code:range.periodCode}).first();if(!period)return null;
  let query=db('goals').where({goal_period_id:period.id}).whereNull('deleted_at');
  if(range.period==='custom')query.where('start_date','>=',range.start).where('end_date','<=',range.end);else query.where('start_date','<=',range.start).where('end_date','>=',range.end);
  if(sellerId){const individuals=await query.clone().where({goal_type:'individual',seller_id:Number(sellerId)});if(individuals.length)return combineGoals(individuals);}
  return combineGoals(await query.where({goal_type:'general'}).whereNull('seller_id'));
}
function combineGoals(rows){if(!rows.length)return null;const columns=['goal_value','morning_value','afternoon_value','portability_base_value','portability_out_value','new_base_value','new_out_value'];const out={ids:rows.map(r=>r.id)};for(const col of columns){const values=rows.filter(r=>r[col]!=null);out[col]=values.length?values.reduce((sum,r)=>sum+Number(r[col]),0):null;}return out;}
function progress(realized,target){if(target==null||Number(target)===0)return{percent:null,status:'neutral'};const percent=realized/Number(target)*100;return{percent,status:percent>=100?'success':percent>=90?'warning':'danger'};}
async function gauge(db,filters,range){const[data,target]=await Promise.all([aggregate(db,filters,range),targetFor(db,range,filters.seller_id)]);return{range,realized:data.totals.revenue,target:target?.goal_value??null,...progress(data.totals.revenue,target?.goal_value)};}
async function getDashboard(db,query,timezone){const range=resolveRange(query,timezone);const filters={seller_id:query.seller_id,service_id:query.service_id,operator_id:query.operator_id,sale_type_id:query.sale_type_id,has_doc:query.has_doc,is_base_sale:query.is_base_sale};const[data,target]=await Promise.all([aggregate(db,filters,range),targetFor(db,range,filters.seller_id)]);const now=DateTime.now().setZone(timezone),standard=rangesFor(now);const gauges=Object.fromEntries(await Promise.all(Object.entries(standard).map(async([key,value])=>[key,await gauge(db,filters,{...value,period:key})])));const dimensionFiltered=Boolean(filters.service_id||filters.operator_id||filters.sale_type_id||filters.has_doc!==undefined&&filters.has_doc!==''||filters.is_base_sale!==undefined&&filters.is_base_sale!=='');return{range,filters,data,target,gauges,progress:progress(data.totals.revenue,target?.goal_value),goalFilterWarning:dimensionFiltered};}
async function references(db){return{ sellers:await db('sellers').where({is_active:true}).orderBy('full_name'),services:await db('services').where({is_active:true}).orderBy('name'),operators:await db('operators').where({is_active:true}).orderBy('name'),saleTypes:await db('sale_types').where({is_active:true}).orderBy('name')};}
module.exports={colorForCode,progress,aggregate,targetFor,getDashboard,references};
