'use strict';
const fs=require('node:fs');const path=require('node:path');const{spawnSync}=require('node:child_process');const ejs=require('ejs');const root=path.resolve(__dirname,'..'),failures=[];
const required=['package.json','package-lock.json','.env.example','src/server.js','src/app.js','src/routes.js','src/views/layouts/main.ejs','src/views/partials/navbar.ejs','scripts/migrate-legacy-sqlite.js'];for(const file of required)if(!fs.existsSync(path.join(root,file)))failures.push(`Ausente: ${file}`);
const files=[];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git'].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else files.push(full);}}walk(root);
for(const file of files){const rel=path.relative(root,file).replaceAll('\\','/'),name=path.basename(file);if(/\.(sqlite3?|db|xlsx?|rar)$/i.test(name)||rel.includes('/uploads/')||/\.(next|final)\./.test(name))failures.push(`Artefato proibido: ${rel}`);if(file.endsWith('.js')){const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});if(result.status!==0)failures.push(`JS inválido ${rel}: ${result.stderr.trim()}`);}if(file.endsWith('.ejs')){try{ejs.compile(fs.readFileSync(file,'utf8'),{filename:file});}catch(error){failures.push(`EJS inválido ${rel}: ${error.message}`);}}}
const trackedEnv=spawnSync('git',['ls-files','--error-unmatch','.env'],{cwd:root,encoding:'utf8'});if(trackedEnv.status===0)failures.push('Artefato proibido rastreado pelo Git: .env');
const sourceFiles=files.filter(f=>(f.includes(`${path.sep}views${path.sep}`)||f.includes(`${path.sep}public${path.sep}`))&&/\.(js|ejs|css)$/.test(f));for(const file of sourceFiles){const text=fs.readFileSync(file,'utf8'),rel=path.relative(root,file);if(text.includes('unsafe-inline'))failures.push(`CSP insegura em ${rel}`);if(text.includes('innerHTML'))failures.push(`innerHTML proibido em ${rel}`);if(/https?:\/\//.test(text))failures.push(`Dependência externa em ${rel}`);if(/style\s*=/.test(text))failures.push(`Estilo inline em ${rel}`);}
const pkg=require(path.join(root,'package.json'));for(const script of['build','start','migrate:deploy','seed:reference','test:run','legacy:inspect','legacy:migrate'])if(!pkg.scripts?.[script])failures.push(`Script npm ausente: ${script}`);require('../src/config/env').loadEnv({NODE_ENV:'test'});
if(failures.length){console.error(failures.join('\n'));process.exit(1);}console.log(`Build verificado: ${files.length} arquivos, JS/EJS, CSP, estrutura e artefatos aprovados.`);
